### ISSUE TITLE
Some typos in ubuntu-xkb-keyboard-remap.md

### ISSUE THREAD

**Issue by zyguan** [Chunlin-Li/Chunlin-Li.github.io#1]
[ubuntu-xkb-keyboard-remap.patch.txt](https://github.com/Chunlin-Li/Chunlin-Li.github.io/files/38688/ubuntu-xkb-keyboard-remap.patch.txt)

BTW，备份是好习惯，不过也可以通过重装 xkb-data 来恢复，前提是还能勉强敲出：

```
sudo apt-get --reinstall install xkb-data
```

重载配置也可以通过 `sudo dpkg-reconfigure xkb-data` 实现，详见 [官方doc](https://help.ubuntu.com/community/Custom%20keyboard%20layout%20definitions#How_to_load_changes)

**Comment by Chunlin-Li** [comment]
@zyguan 
非常感谢! 从没想到会有人看到~  
之前从来不知道 xkb-data 是什么...  学习一下.  
因为有几台不同的电脑, 配置都不太一样, 所以还是用这种方式记住了如果简单的定制 xkb, 以便随时根据需要进行修改

**Comment by zyguan** [comment]
客气，最近看了看 xkb，以应对一些反人类的键盘布局，google 到你这了，写的很清楚，感谢。

xkb-data 就是 debian 系对 xkb 配置文件打了个包而已，没啥大不了的哈。
2015年11月20日 11:33，"Chunlin Li" notifications@github.com写道：
